# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:3.6


stages:
  - lint
  - test_coverage

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - postgres:latest

variables:
  POSTGRES_DB: "postgres"
  TEST: "True"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ~/.cache/pip/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres.
before_script:
  - cd backend && pip install -r requirements.txt

lint:
  stage: lint
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
    - flake8

test:
  stage: test_coverage
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
    DJANGO_SETTINGS_MODULE: "backend.settings-gitlab-ci"
  script:
    - pytest --cov
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
